title: <p align="center">Deepak Hiremath
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="www.linkedin.com/in/deepak-m-hiremath"></a>
  <a href = "https://github.com/deepakhiremath"></a>
  <br>
  I am working on Data Science projects, Big data, Python, Scala, Spark related problems.
  </br></p>

theme: jekyll-theme-minimal
